export const REQUESTLIST = "REQUESTLIST";

export const ACCEPTMONEY = "ACCEPTMONEY";

export const STARTREQUEST = "STARTREQUEST";

export const ARRIVEDREQUEST = "ARRIVEDREQUEST";

export const COMPLETEREQUEST = "COMPLETEREQUEST";