export const REQUESTLIST = "REQUESTLIST";

export const ACCEPTMONEY = "ACCEPTMONEY";

export const STARTREQUEST = "STARTREQUEST";

export const ARRIVEDREQUEST = "ARRIVEDREQUEST";

export const COMPLETEREQUEST = "COMPLETEREQUEST";

export const SUMMARY = "SUMMARY";

export const MONEYOTP = "MONEYOTP";

export const CANCELREQUEST = "CANCELREQUEST";

export const ACCEPTLAUNDRY = "ACCEPTLAUNDRY";

export const LAUNDRYSTATUS = "LAUNDRYSTATUS";

export const CANCELLAUNDRYREQUEST = "CANCELLAUNDRYREQUEST";

export const LAUNDRY_OTP = "LAUNDRY_OTP";

export const LAUNDRY_COMPLETE = "LAUNDRY_COMPLETE";