export const LAUNDRY_ORDER = "LAUNDRY_ORDER";

export const CANCEL_LAUNDRY_ORDER = "CANCEL_LAUNDRY_ORDER"

export const LAUNDRY_PAYMENT = "LAUNDRY_PAYMENT"

export const LAUNDRY_PAYMENT_REJECT = "LAUNDRY_PAYMENT_REJECT"

export const LAUNDRY_RATING = "LAUNDRY_RATING"